apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "staticly.fullname" . }}
  namespace: telekemp
spec:
  hosts:
  - '*'
  gateways:
  - {{ include "staticly.fullname" . }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "staticly.fullname" . }}
        port:
          number: 80
