apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staticly-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - staticly.necrux.com
    secretName: staticly
  rules:
  - host: "staticly.necrux.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: staticly
            port:
              number: 80
